
name: Library application - implementation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo  
      uses: actions/checkout@v3
    - name: Use Node.js 18.*
      uses: actions/setup-node@v3
      with:
        node-version: 18.*
        cache: 'npm'
    - name: Dependencies install
      run: npm install
    - name: Executing unit tests
      run: npm run test:unit
    - name: Dysplaing Softuni username
      run: npm run display:username
